language: generic
sudo: enabled

script: cd DeMark/ && gradle build

after_success:
- gradle check jacocoTestReport
- gradlew check jacocoTestReport coveralls
- ls build/jacocoHtml

after_failure:
- gradle clean check --debug