language: generic
sudo: enabled

script:
- cd DeMark/
- gradle clean build --info

#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

after_success:
- gradle check jacocoTestReport coveralls --debug

after_failure:
- gradle clean check --debug